//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATEC.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public int Code { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public int InviteId { get; set; }
        public string InviteName { get; set; }
        public int ManagerId { get; set; }
        public string ManagerName { get; set; }
        public string IdNumber { get; set; }
        public Nullable<System.DateTime> IdDate { get; set; }
        public string IdProvince1 { get; set; }
        public string IdAddress { get; set; }
        public string IdProvince2 { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string TaxCode { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
        public Nullable<System.DateTime> EmbarkDate { get; set; }
        public Nullable<short> EmbarkLevel { get; set; }
        public bool Disabled { get; set; }
        public bool Deleted { get; set; }
        public bool Actived { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
