//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebApiDbEntities : DbContext
    {
        public WebApiDbEntities()
            : base("name=WebApiDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductCategory> ProductCategories { get; set; }
        public DbSet<ProfitPrice> ProfitPrices { get; set; }
        public DbSet<ProfitStatistic> ProfitStatistics { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<SysGroup> SysGroups { get; set; }
        public DbSet<SysGroupRole> SysGroupRoles { get; set; }
        public DbSet<SysHistory> SysHistories { get; set; }
        public DbSet<SysOption> SysOptions { get; set; }
        public DbSet<SysRole> SysRoles { get; set; }
        public DbSet<SysUser> SysUsers { get; set; }
        public DbSet<SysUserGroup> SysUserGroups { get; set; }
        public DbSet<SysUserOption> SysUserOptions { get; set; }
        public DbSet<SysUserRole> SysUserRoles { get; set; }
        public DbSet<Unit> Units { get; set; }
        public DbSet<Token> Tokens { get; set; }
    }
}
