//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATEC.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public short Quantity { get; set; }
        public double UnitPrice { get; set; }
        public double MarkPrice { get; set; }
        public double Discount { get; set; }
        public string Unit { get; set; }
        public string Description { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
