//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATEC.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfitPrice
    {
        public int CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string Month { get; set; }
        public string PositionName { get; set; }
        public Nullable<double> PV { get; set; }
        public Nullable<double> Direct { get; set; }
        public Nullable<double> Mediate { get; set; }
        public Nullable<double> Periodic { get; set; }
        public Nullable<double> Sun { get; set; }
        public Nullable<double> SysManager { get; set; }
        public Nullable<double> Position { get; set; }
        public Nullable<double> GroupSplit { get; set; }
        public Nullable<double> Agency { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> BeforeTax { get; set; }
        public Nullable<double> AfterTax { get; set; }
        public string Description { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
