//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATEC.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysGroup
    {
        public SysGroup()
        {
            this.SysGroupRoles = new HashSet<SysGroupRole>();
            this.SysUserGroups = new HashSet<SysUserGroup>();
        }
    
        public int Id { get; set; }
        public int Parent { get; set; }
        public string Name { get; set; }
        public bool EnableDelete { get; set; }
        public short SortIndex { get; set; }
        public string Description { get; set; }
        public bool Disabled { get; set; }
        public bool Deleted { get; set; }
        public bool Actived { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual ICollection<SysGroupRole> SysGroupRoles { get; set; }
        public virtual ICollection<SysUserGroup> SysUserGroups { get; set; }
    }
}
