//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATEC.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysRole
    {
        public SysRole()
        {
            this.SysGroupRoles = new HashSet<SysGroupRole>();
            this.SysUserRoles = new HashSet<SysUserRole>();
        }
    
        public int Id { get; set; }
        public string FunctionCode { get; set; }
        public string FunctionName { get; set; }
        public string ParentName { get; set; }
        public byte RLevel { get; set; }
        public short OrderSort { get; set; }
        public string Owner { get; set; }
        public string Description { get; set; }
        public bool Disabled { get; set; }
        public bool Deleted { get; set; }
        public bool Actived { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual ICollection<SysGroupRole> SysGroupRoles { get; set; }
        public virtual ICollection<SysUserRole> SysUserRoles { get; set; }
    }
}
