//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATEC.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUser
    {
        public SysUser()
        {
            this.SysHistories = new HashSet<SysHistory>();
            this.SysUserGroups = new HashSet<SysUserGroup>();
            this.SysUserOptions = new HashSet<SysUserOption>();
            this.SysUserRoles = new HashSet<SysUserRole>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Password { get; set; }
        public bool Disabled { get; set; }
        public bool Deleted { get; set; }
        public bool Actived { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual ICollection<SysHistory> SysHistories { get; set; }
        public virtual ICollection<SysUserGroup> SysUserGroups { get; set; }
        public virtual ICollection<SysUserOption> SysUserOptions { get; set; }
        public virtual ICollection<SysUserRole> SysUserRoles { get; set; }
    }
}
